// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using WebAPIDemoRailway.Data;

#nullable disable

namespace WebAPIDemoRailway.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260320073928_SeedBlogs")]
    partial class SeedBlogs
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("WebAPIDemoRailway.Models.Blog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Author")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("Blogs", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Author = "Nguyễn Văn An",
                            Content = "Python là ngôn ngữ lập trình bậc cao, dễ đọc và dễ học. Bài viết này giới thiệu các khái niệm cơ bản như biến, kiểu dữ liệu, câu lệnh điều kiện và vòng lặp. Phù hợp cho những ai muốn bước chân vào thế giới lập trình.",
                            CreatedAt = new DateTime(2026, 3, 20, 7, 31, 54, 903, DateTimeKind.Utc),
                            Title = "Học lập trình Python cơ bản cho người mới bắt đầu",
                            UpdatedAt = new DateTime(2026, 3, 20, 7, 31, 54, 903, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 2,
                            Author = "Trần Thị Bích",
                            Content = "Đà Lạt vào những tháng cuối năm khoác lên mình màu vàng rực rỡ của hoa dã quỳ. Những cung đường như đèo Prenn, hồ Tuyền Lâm hay đồi chè Cầu Đất trở nên thơ mộng và hấp dẫn du khách. Đừng quên thưởng thức trà nóng và bánh tráng nướng khi đến đây.",
                            CreatedAt = new DateTime(2026, 3, 19, 10, 15, 30, 0, DateTimeKind.Utc),
                            Title = "Khám phá Đà Lạt mùa hoa dã quỳ",
                            UpdatedAt = new DateTime(2026, 3, 20, 8, 20, 45, 123, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 3,
                            Author = "Lê Hoàng Mai",
                            Content = "Phở bò là món ăn truyền thống của Việt Nam, đặc biệt là phở Hà Nội. Bí quyết nằm ở nước dùng được hầm từ xương ống, thêm quế, hồi, gừng nướng và thảo quả. Thịt bò tái chần tới vừa chín tới, ăn kèm bánh phở mềm và rau thơm. Hãy thử ngay tại nhà!",
                            CreatedAt = new DateTime(2026, 3, 18, 2, 45, 12, 456, DateTimeKind.Utc),
                            Title = "Bí quyết nấu phở bò chuẩn vị Hà Nội",
                            UpdatedAt = new DateTime(2026, 3, 18, 14, 30, 22, 789, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 4,
                            Author = "Phạm Minh Quân",
                            Content = "Trí tuệ nhân tạo (AI) tiếp tục bùng nổ với các mô hình ngôn ngữ lớn, ứng dụng trong y tế, giáo dục và sản xuất. Bài viết điểm qua những tiến bộ mới nhất như AI tạo sinh (Generative AI), học tăng cường và các vấn đề đạo đức liên quan.",
                            CreatedAt = new DateTime(2026, 3, 17, 19, 8, 33, 111, DateTimeKind.Utc),
                            Title = "Xu hướng công nghệ AI năm 2026",
                            UpdatedAt = new DateTime(2026, 3, 19, 9, 12, 5, 678, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 5,
                            Author = "Hoàng Thị Thu",
                            Content = "Chạy bộ không chỉ giúp cải thiện sức khỏe tim mạch, tăng cường hệ miễn dịch mà còn giảm căng thẳng, cải thiện tinh thần. Bài viết chia sẻ kinh nghiệm chạy bộ đúng cách, chọn giày phù hợp và xây dựng lộ trình cho người mới.",
                            CreatedAt = new DateTime(2026, 3, 16, 5, 22, 44, 567, DateTimeKind.Utc),
                            Title = "Lợi ích của việc chạy bộ mỗi sáng",
                            UpdatedAt = new DateTime(2026, 3, 17, 12, 34, 56, 789, DateTimeKind.Utc)
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
